variables:
  VERSION: "$CI_PIPELINE_ID"
  ASPNETCORE_ENVIRONMENT: "Production"

stages:
  - build
  - update_github
  - test
  - update_gitops

before_script:
  - eval "$(ssh-agent -s)"
  - cat ~/.ssh/id_rsa | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo $GITHUB_URL

build-user-service:
  stage: build
  only:
    - master
  script:
    - docker-compose -f docker-compose-user-service.yml build
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose -f docker-compose-user-service.yml push

build-identity-server:
  stage: build
  only:
    - master
  script:
    - docker-compose -f docker-compose-identity-server.yml build
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose -f docker-compose-identity-server.yml push

update-github:
  stage: update_github
  only:
    - master
  script:
    - ssh git@github.com || true
    - git remote remove origin && git remote add origin $GITHUB_URL
    - git config --global --add safe.directory $(pwd)
    - git fetch --unshallow $GITHUB_URL || true
    - git push origin HEAD:master -f
    - git config --global --unset safe.directory $(pwd) || true

test:
  stage: test
  only:
    - master
  needs:
    - build-user-service
    - build-identity-server
  script:
    - docker build -t test-business:latest -f TestMaker.TestService.UnitTests/Dockerfile .
    - docker run --rm -t test-business:latest dotnet test --logger:"console;verbosity=normal"
    - docker image rm test-business:latest
        
update-gitops:
  stage: update_gitops
  only:
    - master
  needs: [test]
  script:
    - echo "update-gitops"
    #- git clone $GITOPS_URL 
    #- cd GitOps
    #- git config --global --add safe.directory $(pwd)
    #- git checkout -b test-maker origin/test-maker
    #- sed -i "s/test-maker.test-service:[0-9]*/test-maker.test-service:$VERSION/g" ./setup/test-service.deployment.yml
    #- git add ./setup/test-service.deployment.yml
    #- git config --global user.email "kinhnv1801@gmail.com"
    #- git config --global user.name "Nguyen Van Kinh"
    #- git commit -m "change to version $VERSION"
    #- git push origin test-maker
    #- git config --global --unset safe.directory $(pwd) || true